In [5]:
from cleaning_data import *
import re
import pandas as pd

dirty_data = load_csv("dirty_dataset.csv")
dirty_data

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,unknown,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,NaN,NaN
1,2824,Fulvio Sismondin/a,fiannuzzi,NaN,09-03-2025,not_available,IT,Acquaron/a,498.08,??,IV59,2,many,yes
2,NaN,Elisa Simeoni??,silvestrirolando@example.com,-5,10/03/2022,05-27-2025,Italia,Campestrinxxx,169.87,Fashion,NaN,4,many,no
3,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,NaN,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,NaN,True
4,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,NaN,2023-08-19,NaN,Italia,San Vincenzo A Torri,"455,25",Tech,FT44,NaN,715,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50995,8249,Renzo Draghixxx,pier97@example.com,58,13-09-22,NaN,italy,Muriscuvo'NULL,224.03,HOME,NaN,5,NaN,False
50996,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,-5,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,NaN,True
50997,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,-5,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,NaN,no
50998,NaN,Ruggiero Marangoni,roccoborsellino@example.com,unknown,23/08/2025,not_available,italy,Schennan/a,365.38,Home,NaN,5,many,no
50999,3426,Guglielmo Micheletti-Fattori###,ferdinandonaccari@example.org,78,01/01/2023,10-02-2022,Italy,Portosecco,469.38,HOME,TG57,five,many,True

In [6]:
regex = r'^(?![a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$)'
filtred_id = clean_pattern_column(dirty_data, "user_id", regex)
filtred_id.dropna(subset=["user_id"], inplace=True)
filtred_id

,user_id,name,email,age,signup_date,last_login,country,city,purchase_amount,category,discount_code,rating,reviews_count,returned
0,788f3808-bc11-4555-81c0-82de2928ebe9,Ivo Riccardixxx,pietrobertolucci@example.org,unknown,24-11-23,not_available,NaN,Pandola###,249.72,??,NaN,1,NaN,NaN
3,c8db0ce6-2f8f-4699-8e2a-c3af367f0742,Daria Vanvitellin/a,rosa95@example.net,NaN,04-03-24,NaN,NaN,Governolo,77.61,??,NaN,five,NaN,True
4,cddf2e27-d51f-4e6c-85aa-ba3c634a10ca,Beatrice Tencalla,dossettipasquale,NaN,2023-08-19,NaN,Italia,San Vincenzo A Torri,"455,25",Tech,FT44,NaN,715,no
6,bedd5433-0834-44f7-ac07-97c08027a2be,Emma Dibiasixxx,cleliabrambilla@example.com,NaN,11-11-2021,2023/10/29,Italy,Terrasinin/a,99.88,fashion,NaN,3,NaN,yes
7,d5c99441-b19a-4d5f-8261-79e93b7e009a,Anita Volta??,avitturi@example.com,-5,2021-12-05,11-02-24,IT,Mezzolara,387.03,TEC,fB81,4,58,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50990,0d6f55aa-3b6d-4346-9709-9f04b1daf8ab,Aurora Curiel-Canova###,ferrarisronaldo@example.org,21,2024/11/16,not_available,Italia,Umbra,"215,96",Home,NaN,3,many,False
50991,03f60bd8-3c8e-4f79-9a9e-b186fe16a042,Priscilla Letta-Capone,amaldiiolanda@example.com,65,2024/12/31,10-14-2021,NaN,Tarzo,433.67,TEC,NaN,3,many,NaN
50992,07380440-2046-4a09-b968-cf0a267885ae,Elmo Mogherini-Perini,vemanuelli@example.com,unknown,2025/08/11,23-05-23,Italy,Bricherasio??,356.81,Tech,NaN,5,NaN,yes
50996,1f4ecb21-3467-4539-b88e-b046b891b15f,Mercedes Boezioxxx,igolino@example.com,-5,2023-02-19,NaN,Italy,Ridotti,338.18,??,NaN,five,NaN,True
50997,88834303-7350-4c9b-8600-06fbbf79f9af,Rossana Ciampi,livia65@example.org,-5,18-10-24,NaN,italy,Grignanon/a,379.41,Tech,NaN,NaN,NaN,no